const styles = {
  pageBackground: {
    display: 'flex',
    justifyContent: 'center',
    flexDirection: 'column',
    minHeight: '55vh',
    maxWidth: '900px',
    margin: '0 auto',
    backgroundColor: '#f0f2f5',
    fontFamily: 'Arial, sans-serif', 
    borderRadius: '12px',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.1)',
    boxSizing: 'border-box',
  },
  container: {
    width: '700px',
    height: '500px', 
    margin: '30px auto',
    padding: '40px',
    borderRadius: '12px',
    boxShadow: '0 4px 10px rgba(0, 0, 0, 0.1)',
    backgroundColor: '#ffffff', 
    fontFamily: 'Arial, sans-serif',
  },
  
  heading: {
    color: '#2c3e50',
    textAlign: 'center',
    marginBottom: '30px',
    fontSize: '36px',
    fontWeight: 'bold',
  },
  formGroup: {
    marginBottom: '20px',
  },
  label: {
    display: 'block',
    marginBottom: '5px',
    fontWeight: 'bold',
    color: '#555',
  },
  input: {
    width: '100%',
    padding: '10px',
    borderRadius: '5px',
    border: '1px solid #ccc',
    fontSize: '16px',
    outline: 'none',
    boxSizing: 'border-box',
    marginBottom: '15px',
    transition: 'border-color 0.3s ease',
  },
  button: {
    padding: '12px 20px',
    backgroundColor: '#f97316',
    borderRadius: '5px',
    border: 'none',
    color: 'white',
    fontSize: '16px',
    cursor: 'pointer',
    marginTop: '20px',
    transition: 'background-color 0.3s ease',
    textAlign: 'center',
    width: '100%',
  },
  editButton: {
    backgroundColor: '#3498db',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '5px',
    cursor: 'pointer',
    fontSize: '14px',
    marginTop: '10px',
    width: '100%',
    textAlign: 'center',
    transition: 'background-color 0.3s ease',
  },
  buttonContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '10px',
  },
  footer: {
    marginTop: 'auto',
    textAlign: 'center',
    padding: '10px 0',
    borderTop: '1px solid #ccc',
    color: '#777',
    fontSize: '14px',
  },
  successMessage: {
    color: 'green', 
    fontSize: '16px', 
    marginBottom: '10px',
    textAlign: 'center', 
    width: '100%', 
  },
  error: {
    color: 'red', 
    fontSize: '16px',
    marginTop: '-10px', 
    marginBottom: '10px',
  },
  errorMessage: {
    color: 'red', 
    fontSize: '16px',
    marginTop: '-10px', 
    marginBottom: '10px',
  },
};

export default styles;