const styles = {
    container: {
      display: 'flex',
      flexDirection: 'column',
      minHeight: '75vh',
      maxWidth: '1200px',
      margin: '0 auto',
      padding: '30px',
      backgroundColor: '#f0f2f5',
      borderRadius: '12px',
      fontFamily: 'Arial, sans-serif',
      boxShadow: '0 4px 10px rgba(0, 0, 0, 0.1)',
      boxSizing: 'border-box',
    },
    heading: {
      color: '#2c3e50',
      textAlign: 'center',
      marginBottom: '30px',
      fontSize: '36px',
      fontWeight: 'bold',
    },
    subHeading: {
      color: '#f97316',
      marginBottom: '20px',
      fontSize: '24px',
      fontWeight: 'bold',
      borderBottom: '2px solid #3498db',
      paddingBottom: '10px',
    },
    form: {
      backgroundColor: '#ffffff',
      padding: '25px',
      borderRadius: '10px',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
      marginBottom: '30px',
    },
    textarea: {
      width: '100%',
      minHeight: '100px',
      padding: '10px',
      borderRadius: '5px',
      border: '1px solid #ccc',
      fontSize: '14px',
      marginBottom: '15px',
    },
    select: {
      padding: '8px',
      borderRadius: '5px',
      border: '1px solid #ccc',
      backgroundColor: '#fff',
      fontSize: '14px',
      marginBottom: '15px',
      marginRight: '15px',
    },
    button: {
      padding: '10px 20px',
      backgroundColor: '#f97316',
      color: '#ffffff',
      border: 'none',
      borderRadius: '5px',
      fontWeight: 'bold',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease-in-out',
    },
    ticketList: {
      listStyle: 'none',
      padding: 0,
    },
    ticketItem: {
      backgroundColor: '#ffffff',
      padding: '20px',
      borderRadius: '10px',
      boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
      marginBottom: '20px',
    },
    ticketHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: '15px',
    },
    ticketTitle: {
      fontSize: '20px',
      fontWeight: 'bold',
      color: '#2c3e50',
    },
    ticketStatus: {
      padding: '5px 10px',
      borderRadius: '15px',
      fontWeight: 'bold',
      fontSize: '14px',
    },
    ticketInfo: {
      marginBottom: '10px',
      fontSize: '16px',
    },
    label: {
      fontWeight: 'bold',
      color: '#555',
      marginRight: '10px',
    },
    deleteButton: {
      padding: '5px 10px',
      backgroundColor: '#e74c3c',
      color: '#ffffff',
      border: 'none',
      borderRadius: '5px',
      cursor: 'pointer',
      transition: 'background-color 0.2s ease-in-out',
    },
    filterContainer: {
      marginBottom: '20px',
      display: 'flex',
      alignItems: 'center',
    },
  };
  
  export default styles;