const styles = {
  exploreVehicles: {
    padding: "60px 80px",
    backgroundColor: "#f5f5f5",
  },
  exploreVehiclesHeading: {
    marginLeft: "20px", 
    marginTop: "20px", 
  },
  vehicleGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "20px",
    padding: "20px 25px",
  },
  vehicleCard: {
    borderRadius: "8px",
    textAlign: "left",
    width: "100%",
    backgroundColor: "white",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
    overflow: "hidden",
  },
  vehicleCardImg: {
    width: "100%",
    height: "250px",
    objectFit: "cover",
    borderRadius: "8px 8px 0 0",
  },
  vehicleCardContent: {
    padding: "12px 25px",
  },
  vehiclePrice: {
    fontWeight: "bold",
    fontSize: "1.2em",
    color: "#333",
  },
  viewDetailsLink: {
    color: "orange",
    cursor: "pointer",
    display: "inline-block",
    textDecoration: "none",
  },
  tiltedArrow: {
    display: "inline-block",
    transform: "rotate(-45deg)",
    marginLeft: "5px",
  },
  carDetailsModal: {
    position: "fixed",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  carDetailsContent: {
    backgroundColor: "white",
    padding: "30px",
    borderRadius: "10px",
    maxWidth: "950px",
    width: "90%",
    position: "relative",
  },
  closeLink: {
    position: "absolute",
    top: "10px",
    right: "15px",
    fontSize: "24px",
    color: "#333",
    cursor: "pointer",
  },
  carDetailsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "20px",
  },
  carDetailsImageImg: {
    width: "100%",
    height: "auto",
    borderRadius: "8px",
  },
  carDetailsInfoH2: {
    color: "#333",
  },
  carDetailsInfoP: {
    margin: "6px 0",
    color: "#666",
  },
  searchAndFilterContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '20px',
    flexWrap: 'wrap',
    gap: '10px',
    backgroundColor: '#ffffff',
    padding: '15px',
    borderRadius: '8px',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  searchInput: {
    padding: '10px',
    fontSize: '1em',
    borderRadius: '5px',
    border: '1px solid #ccc',
    width: '200px',
    flex: '1 1 200px',
  },
  filterSelect: {
    padding: '10px',
    fontSize: '1em',
    borderRadius: '5px',
    border: '1px solid #ccc',
    flex: '1 1 150px',
    appearance: 'none',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 10px top 50%',
    backgroundSize: '12px auto',
  },
  paginationContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '20px',
  },
  paginationButton: {
    padding: '10px 20px',
    fontSize: '1em',
    backgroundColor: '#f97316',
    color: 'white',
    border: 'none',
    borderRadius: '5px',
    cursor: 'pointer',
    margin: '0 10px',
  },
  pageInfo: {
    fontSize: '1em',
    margin: '0 10px',
  },
  bookButton: {
    backgroundColor: '#f97316',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '5px',
    cursor: 'pointer',
    marginLeft: '50px',
  },
  actionButtons: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: '10px',
  },
  bookCarButton: {
    backgroundColor: '#f97316',
    color: 'white',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '5px',
    cursor: 'pointer',
    marginTop: '30px',
  },
  searchResult: {
    fontSize: '32px', 
    textAlign: 'center', 
    marginTop: '30px', 
  },
  // New styles for the price range slider
  priceRangeContainer: {
    display: 'flex',
    flexDirection: 'column',
    width: '300px',
    margin: '10px 0',
  },
  priceRangeSlider: {
    width: '100%',
    appearance: 'none',
    height: '5px',
    borderRadius: '5px',
    background: '#ddd',
    outline: 'none',
    opacity: '0.7',
    transition: 'opacity .2s',
    '&:hover': {
      opacity: '1',
    },
    '&::-webkit-slider-thumb': {
      appearance: 'none',
      width: '20px',
      height: '20px',
      borderRadius: '50%',
      background: '#f97316',
      cursor: 'pointer',
    },
    '&::-moz-range-thumb': {
      width: '20px',
      height: '20px',
      borderRadius: '50%',
      background: '#f97316',
      cursor: 'pointer',
    },
  },
  priceRangeLabels: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '5px',
  },
  priceRangeLabel: {
    fontSize: '0.9em',
    color: '#666',
  },
};

export { styles };